server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456