server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&serverTimezone=PRC&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456